# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-23 09:12+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:108
msgid "The URL field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../gecosws_config_assistant/controller/AutoSetupController.py:163
#: ../gecosws_config_assistant/controller/AutoSetupController.py:171
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:123
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:131
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:196
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:228
#: ../gecosws_config_assistant/controller/LocalUserController.py:78
#: ../gecosws_config_assistant/controller/LocalUserController.py:94
#: ../gecosws_config_assistant/controller/LocalUserController.py:103
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:367
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:382
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:412
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:438
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:447
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:456
#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:123
msgid "Please fill all the mandatory fields."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:115
msgid "Malformed URL in URL field!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:115
msgid "Please double-check it."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:127
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:150
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:434
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:546
msgid "The certificate of this server is expired!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:129
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:152
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:436
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
msgid "The certificate of this server is not trusted!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:132
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:155
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:440
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:551
msgid "Do you want to disable the SSL certificate verification?"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:134
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:157
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:553
msgid "Subject:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:135
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:158
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:443
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:554
msgid "Issuer:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:136
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:159
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:444
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:555
msgid "Serial Number:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:137
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:160
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:445
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:556
msgid "Not before:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:137
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:160
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:445
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:556
msgid "Not after:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:152
#: ../gecosws_config_assistant/controller/AutoSetupController.py:179
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:183
msgid "Can't connect to GECOS CC!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:152
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:465
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:576
msgid "SSL ERROR:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:163
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:123
msgid "The Username field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:171
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:131
msgid "The Password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:179
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:183
msgid "Please double-check all the data and your network setup."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:201
msgid "Please wait"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:211
msgid "Error getting data"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:212
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:217
msgid "Success getting data from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:196
msgid "The GECOS workstation name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:215
msgid "The GECOS workstation name already exist!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:215
msgid "Please choose a different name."
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:228
msgid "You must select an OU!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
msgid "Link to Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:326
msgid "Register in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:331
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:354
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:364
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:649
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:679
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:702
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:711
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:721
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:731
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:796
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:809
msgid "IN PROCESS"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:335
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:341
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:347
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:357
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:384
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:394
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:450
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:463
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:478
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:491
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:561
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:574
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:598
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:613
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:658
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:704
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:714
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:740
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:753
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:762
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:773
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:782
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:799
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:106
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:111
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:116
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:125
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:134
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:139
msgid "ERROR"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:351
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:501
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:646
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:684
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:708
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:718
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:728
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:793
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:806
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:815
msgid "DONE"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:386
msgid "There was an error while getting the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:396
msgid "There was an error while saving the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:465
msgid "Can't connect to GEMs repository!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:480
msgid "There was an error while adding the GEMs repository:\n"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:493
msgid "There was an error while installing a required GEM: "
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:576
msgid "Can't connect to Chef Server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:600
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:615
msgid "Can't link to chef server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:638
msgid "Can't create/modify /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:660
msgid "Can't register the computer in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:670
msgid "Can't save /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:696
msgid "Unlink from Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:697
msgid "Unregister from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:742
msgid "Can't unregister the computer from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:755
msgid "Can't remove /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:764
msgid "Can't remove /etc/chef/client.pem file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:775
msgid "Can't delete Chef node"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:784
msgid "Can't remove /usr/bin/chef-client-wrapper file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:801
msgid "Can't remove /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:835
msgid "Can't get OUs from GECOS Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:78
msgid "The login field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:85
msgid "The login field contains not allowed characters!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:94
msgid "The name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:103
msgid "The password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:111
msgid "The password field contains not allowed characters."
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:160
msgid "Do you really want to delete this user? "
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:181
msgid "The system has a network connection configured"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:183
msgid "The system has NO network connection"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:186
msgid "The system has loaded setup data values from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:188
msgid "The system may load setup data values from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:191
msgid "The system is synchronized with a NTP server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:193
msgid "The system is NOT synchronized with a NTP server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:196
msgid "The system is linked to a GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:198
msgid "The system is NOT linked to a GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:200
#, python-format
msgid "Users authenticate by %s method"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:205
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:230
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../gecosws_config_assistant/view/UserAuthDialog.py:189
msgid "LDAP"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:207
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:232
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:149
#: ../gecosws_config_assistant/view/UserAuthDialog.py:191
msgid "Active Directory"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:209
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../gecosws_config_assistant/view/UserAuthDialog.py:187
msgid "Internal"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:272
msgid "Are you sure you want to update the GECOS Config Assistant?"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:275
#: ../gecosws_config_assistant/controller/MainMenuController.py:283
msgid "An error occurred during the upgrade"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:279
msgid "CGA is already at the newest version!"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:281
msgid "GECOS Config Assistant has been udpated. Please restart GCA"
msgstr ""

#: ../gecosws_config_assistant/controller/NTPServerController.py:87
#: ../gecosws_config_assistant/controller/NTPServerController.py:91
msgid "Error saving NTP server data."
msgstr ""

#: ../gecosws_config_assistant/controller/NTPServerController.py:87
#: ../gecosws_config_assistant/controller/NTPServerController.py:91
#: ../gecosws_config_assistant/view/UserAuthDialog.py:408
msgid "See log for more details."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:302
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:367
msgid "The URI field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:374
msgid "Malformed LDAP URI!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:374
msgid "Please check that the URI starts with 'ldap://' or 'ldaps://'."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:382
msgid "The users base DN field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:389
msgid "Can't connect to LDAP server!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:389
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:464
msgid "Please check all the fields and your network connection."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:404
msgid "Bad netbios hostname!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:404
msgid "Please change the hostname of this computer."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:412
msgid "The Domain field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:429
msgid "Can't resolv the Active Directory Domain name!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:430
msgid "Please check the Domain field and your DNS configuration."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:438
msgid "The Workgroup field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:446
msgid "The AD administrator user field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:455
msgid "The AD administrator password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:463
msgid "Can't connect to Active Directory server!"
msgstr ""

#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:118
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
msgid "Disconnect from CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:161
msgid "Connect to CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:84
msgid "Modifiy local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:90
msgid "Add local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:122
msgid "The password confirmation field is empty!"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:130
msgid "The password confirmation is different from password"
msgstr ""

#: ../gecosws_config_assistant/view/LogTerminalDialog.py:110
msgid "Log terminal"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:168
msgid "Link with GECOS server"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:170
msgid ""
"You must link your workstation with a GECOS server to be \n"
"able to manage this workstation in a centralized way"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:178
msgid "Setup user authentication method"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:180
msgid ""
"You must setup the user authentication method to either: internal users, "
"LDAP or Active Directory"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:356
msgid "Unlink"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:115
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:118
msgid "NTP server connection successful"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:87
msgid "System status"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:92
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:94
msgid "Assistant version: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:94
msgid "UNKNOWN VERSION"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:99
msgid "Workstation name: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:104
msgid "Time server: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:107
msgid "Network interfaces: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:113
msgid "GECOS Control Center connection data: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:116
msgid "Server URL:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:117
msgid "Login:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:120
msgid "Local users: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:127
msgid "User authentication method: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:130
msgid "Method:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:133
#: ../gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../gecosws_config_assistant/view/UserAuthDialog.py:278
msgid "Domain:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:134
#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../gecosws_config_assistant/view/UserAuthDialog.py:279
msgid "Workgroup:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:137
msgid "Server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:138
#: ../gecosws_config_assistant/view/UserAuthDialog.py:215
msgid "Users base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:139
msgid "Groups base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:144
msgid "No status data!"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:211
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
msgid "LDAP server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
msgid "Groups base DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:217
msgid "Bind user DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:218
msgid "Bind user password (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:243
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:248
msgid "(Active Directory) User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:249
msgid "(Active Directory) Password:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:274
msgid ""
"Specific configuration data was loaded from GECOS server\n"
" (sssd.conf, krb5.conf, smb.conf and pam.conf)"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:280
msgid "User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:281
msgid "Password:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:307
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:408
msgid "An error happened while saving the users authentication method!"
msgstr ""
